KITTI:
  PATH:
    img_dirs:
      - "./data/KITTI/sequences/00/image_0/%06d.png"
      - "./data/KITTI/sequences/00/image_1/%06d.png"
    calibration: 
      "./data/KITTI/sequences/00/calib.txt"
    timestamp: 
      "./data/KITTI/sequences/00/times.txt"
    